(defun read-grid-from-file (filename rows cols)
  (with-open-file (in filename)
    (let ((grid (make-array (list rows cols) :element-type 'character)))
      (dotimes (r rows)
        (let ((line (read-line in nil nil)))
          (unless (and line (= (length line) cols))
            (error "File format error: line ~A is missing or wrong length" (1+ r)))
          (dotimes (c cols)
            (setf (aref grid r c) (char line c)))))
      grid)))

(defun count-4-letter-word-occurrences (grid word)
  (let* ((directions '((0 1) (0 -1) (1 0) (-1 0) (1 1) (1 -1) (-1 1) (-1 -1)))
         (rows (array-dimension grid 0))
         (cols (array-dimension grid 1))
         (word-length (length word))
         (count 0))
    (dotimes (row rows)
      (dotimes (col cols)
        (when (char= (aref grid row col) (char word 0))
          (dolist (dir directions)
            (let* ((delta-row (first dir))
                   (delta-col (second dir))
                   (end-row (+ row (* delta-row (- word-length 1))))
                   (end-col (+ col (* delta-col (- word-length 1)))))
              (when (and (>= end-row 0) (< end-row rows)
                         (>= end-col 0) (< end-col cols))
                (let ((matched t))
                  (loop for i from 1 below word-length do
                    (let ((r (+ row (* delta-row i)))
                          (c (+ col (* delta-col i))))
                      (unless (char= (aref grid r c) (char word i))
                        (setf matched nil)
                        (return))))
                  (when matched
                    (incf count)))))))))
    count))

;; Usage example:

(let* ((filename "/home/rye/development/lisp/advent-of-code-2024/day4/day4.dat")  ; replace with your actual filename
       (rows 140)
       (cols 140)
       (word "XMAS")
       (grid (read-grid-from-file filename rows cols))
       (occurrences (count-4-letter-word-occurrences grid word)))
  (format t "The word \"~A\" appears ~D times in the grid.~%" word occurrences))
